name: Tests

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
    -
      name: checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    -
      name: python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    -
      name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    -
      name: isort and flake8
      run: |
        isort . --check
        flake8 setup.py rendor.py tests

    -
      name: Run tests
      run: pytest
